# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jessica Temporal
email: hello@jtemporal.com
description: > # this means to ignore newlines until "baseurl:"
  Sr. Developer Advocate, Podcaster @ Pizza de Dados, Speaker and Technical Blogger. my pronouns are she/her/they.
  This is my personal blog, my opinions are my own.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jtemporal.com" # the base hostname & protocol for your site

# reading time
reading_time: true
words_per_minute: 200

#sidebar
default-image: logo.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: 

copyright:
   name: Jessica Temporal
   link: 'https://jtemporal.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 30
paginate_path: /page:num/

# Tracker
analytics: UA-89599031-1
tagmanager: GTM-KKCR3VG

# Comments

#social
twitter:
  username: jesstemporal
  card: summary_large_image
github: https://github.com/jtemporal

# Collections
collections:
  - hacktoberfest_projects

# Sass style
sass:
  style: compressed

# Include list
include: [.well-known, EnJtResume.pdf, folium]

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
