# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jessica Temporal
tagline: Posts about python, data science, git, open source and more ğŸ˜‰
email: hello@jtemporal.com
description: > # this means to ignore newlines until "baseurl:"
  Sr. Dev Advocate ğŸ¥‘ â€¢ ğŸ™ Podcaster @pizzadedados â€¢ Creator of @gitfichas â€¢ GitHub â­ï¸ â€¢ cross stitch & knitter â€¢ ğŸ‡§ğŸ‡· & ğŸ‡¨ğŸ‡¦ â€¢ she/her â€¢
  Opinions are my own.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jtemporal.com" # the base hostname & protocol for your site

# reading time
reading_time: true
words_per_minute: 200

#sidebar
default-image: logo.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.
favicon: https://res.cloudinary.com/jesstemporal/image/upload/v1671381240/favicon_p3m2nf.ico
applefavicon: https://res.cloudinary.com/jesstemporal/image/upload/v1671381215/apple-touch-icon_ka9zbv.png

#footer
built-by: 

copyright:
   name: Jessica Temporal
   link: 'https://jtemporal.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 30
paginate_path: /page:num/

# Tracker
analytics: UA-89599031-1
tagmanager: GTM-KKCR3VG

# Comments

#social
twitter:
  username: jesstemporal
  card: summary_large_image
github: https://github.com/jtemporal

# boks:
#   microbook:
#     gumroad:
#     amazon:

# Collections
collections:
  hacktoberfest_projects:
    projects: true
  books:
      output: true

# Sass style
sass:
  style: compressed

# Include list
include: [.well-known, EnJtResume.pdf, folium]

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
