# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jessica Temporal
tagline: Posts about python, data science, git, open source and more ğŸ˜‰
email: hello@jtemporal.com
description: > # this means to ignore newlines until "baseurl:"
  Sr. Dev Advocate ğŸ¥‘ â€¢ ğŸ™ Podcaster @pizzadedados â€¢ Creator of @gitfichas â€¢ GitHub â­ï¸ â€¢ cross stitch & knitter â€¢ ğŸ‡§ğŸ‡· & ğŸ‡¨ğŸ‡¦ â€¢ she/her â€¢
  Opinions are my own.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# reading time
reading_time: true
words_per_minute: 200

#sidebar
default-image: /images/logo.webp # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.
favicon: https://res.cloudinary.com/jesstemporal/image/upload/v1671381240/favicon_p3m2nf.ico
applefavicon: https://res.cloudinary.com/jesstemporal/image/upload/v1671381215/apple-touch-icon_ka9zbv.png

#footer
built-by: 

copyright:
   name: Jessica Temporal
   link: 'https://jtemporal.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 30
paginate_path: /page:num/

# Multi-language configuration
languages:
  en:
    flag: "ğŸ‡ºğŸ‡¸"
    name: "English"
    code: "en"
    locale: "en_US"
    url: "/en/"
    text:
      know_more_button: "Learn more"
      buy_button: "Buy on"
      recent_articles_title: "Recent Articles"
      related_articles_title: "Related Articles"
      author_note_title: "Author Note"
  pt:
    flag: "ğŸ‡§ğŸ‡·"
    name: "PortuguÃªs" 
    code: "pt"
    locale: "pt_BR"
    url: "/pt/"
    text:
      know_more_button: "Saiba mais"
      buy_button: "Compre na"
      recent_articles_title: "Artigos recentes"
      related_articles_title: "Artigos relacionados"
      author_note_title: "Nota da autora"

# Default language
default_language: en

# Tracker
analytics:
tagmanager:

#social
twitter:
  username: jesstemporal
  card: summary_large_image
github: https://github.com/jtemporal

banner_books:
  en:
    book:
      title: "The Big Git Microbook"
      subtitle: "A quick guide to commands you will use daily"
      page: "/gitmicrobook"
      cover: "/images/books/gitmicrobook-ipad-no-bg.webp"
      short_description: "What if you could have a Git dictionary? A book where you could find a description of how the most commonly used commands work, with practical examples?"
      gumroad: https://jessicatemporal.gumroad.com/l/gitmicrobook?wanted=true
      amazon: https://www.amazon.com/dp/B0CDNX6NS7/ref=sr_1_1?&_encoding=UTF8&tag=jesstempora0e-20&linkCode=ur2&linkId=efc4229f6b816609dfce4f185781d99a&camp=1789&creative=9325
  pt:
    book:
      title: "O Grande Microlivro de Git"
      subtitle: "Um guia rÃ¡pido para comandos que vocÃª usarÃ¡ diariamente"
      page: /microlivrodegit
      cover: /images/livros/microlivro-de-git-ipad.webp
      short_description: "E se vocÃª pudesse ter um dicionÃ¡rio de Git? Um livro onde vocÃª encontrasse uma descriÃ§Ã£o do funcionamento dos comandos mais comuns utilizados no dia-a-dia, com exemplos prÃ¡ticos?"
      gumroad: https://jessicatemporal.gumroad.com/l/microlivrodegit?wanted=true
      amazon: https://amzn.to/3SETpx4

# Collections
collections:
  books:
      output: true
  hacktoberfest_projects_2019:
    projects: true
  hacktoberfest_projects_2020:
    projects: true
  hacktoberfest_projects_2021:
    projects: true
  hacktoberfest_projects_2022:
    projects: true
  hacktoberfest_projects_2023:
    projects: true
  hacktoberfest_projects_2024:
    projects: true
  hacktoberfest_projects_2025:
    projects: true

# Sass style
sass:
  style: compressed

# Include list
include: [.well-known, EnJtResume.pdf, folium, llms.txt]

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-redirect-from]
